apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: private-azurefile-csi-nfs
  resources:
    requests:
      storage: 100Gi